[build]
  command = "cd docs-site && pnpm install && pnpm docs:build"
  publish = "docs-site/.vitepress/dist"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "8.15.4"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'"