name: 🐛 Bug Report
description: Create a report to help us improve PGRestify
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of PGRestify
          required: true
        - label: I have read the documentation
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create client with...
        2. Execute query...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      placeholder: |
        ```typescript
        import { createClient } from '@webcoded/pgrestify';
        
        const client = createClient({
          url: 'http://localhost:3000'
        });
        
        // Your code that reproduces the issue
        ```
      render: typescript
    validations:
      required: false

  - type: dropdown
    id: package-version
    attributes:
      label: PGRestify Version
      description: Which version of PGRestify are you using?
      options:
        - 1.1.0 (latest)
        - 1.0.0
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework
      description: Which framework are you using?
      options:
        - React
        - Next.js (App Router)
        - Next.js (Pages Router)
        - Vanilla TypeScript/JavaScript
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running?
      placeholder: e.g., 18.17.0
    validations:
      required: true

  - type: input
    id: postgrest-version
    attributes:
      label: PostgREST Version
      description: What version of PostgREST are you using?
      placeholder: e.g., 11.2.0
    validations:
      required: false

  - type: input
    id: postgres-version
    attributes:
      label: PostgreSQL Version
      description: What version of PostgreSQL are you using?
      placeholder: e.g., 14.9
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: In which environment does this issue occur?
      options:
        - Development
        - Production
        - Both
        - Testing
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error logs or console output
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help us understand the issue...

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      description: How does this bug affect you?
      options:
        - label: Blocks development
        - label: Causes data corruption
        - label: Performance issue
        - label: Security concern
        - label: Minor inconvenience