blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/webcodedsoft/pgrestify-v1/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://pgrestify.netlify.app
    about: Read our comprehensive documentation and guides
  - name: 💡 Feature Ideas & Roadmap
    url: https://github.com/webcodedsoft/pgrestify-v1/discussions/categories/ideas
    about: Share feature ideas and see what's planned for the future
  - name: 🆘 Get Help
    url: https://github.com/webcodedsoft/pgrestify-v1/discussions/categories/q-a
    about: Get help from the community and maintainers